export const CHANGE_BANNER = "CHANGE_BANNER";
export const CHANGE_HOTRECOMMEND = "CHANGE_HOTRECOMMEND";
export const CHANGE_NEWALBUM="CHANGE_NEWALBUM";

export const CHANGE_UPRANKING="CHANGE_UPRANKING";
export const CHANGE_NEWRANKING="CHANGE_NEWRANKING";
export const CHANGE_ORIGINALRANKING="CHANGE_ORIGINALRANKING";
 
// 获取入住歌手列表，10条
export const CHANGE_SETTLESINGER='CHANGE_SETTLESINGER';





